### ISSUE TITLE
Update to FX 17.0.2 to fix problem on OSX?

### ISSUE THREAD

**Issue by sten-navie** [gluonhq/rich-text-area#1]
Got a crash on my OSX machine (Montereys, M1). Works if I change the FX version from 17.0.1 to 17.0.2.

Seems I encountered https://bugs.openjdk.java.net/browse/JDK-8275723

**Comment by abhinayagarwal** [comment]
Fixed with https://github.com/gluonhq/rich-text-area/commit/e30b6434bab6cff1567d6357d8be43349efda52b
