### ISSUE TITLE
Undo / redo inconsistencies

### ISSUE THREAD

**Issue by dlemmermann** [gluonhq/rich-text-area#104]
I noticed inconsistencies when undoing / redoing editing operations. Additional "no-ops" undo steps were executed when pressing the undo button. It also seemed as if the selection state gets put onto the undo stack. In the end I could not undo anymore even though there should have been more undoable steps. A last thing I noticed was that the caret was placed at strange places when undoing edits.

https://user-images.githubusercontent.com/9534301/157874218-c9079ad8-5310-4ba5-90e2-b84296bad311.mov

**Comment by jperedadnr** [comment]
Fixed with #106
