### ISSUE TITLE
Selecting a text range via mouse drag stops working when cursor leaves editor

### ISSUE THREAD

**Issue by dlemmermann** [gluonhq/rich-text-area#135]
I noticed that selecting a text range stopped working when the mouse cursor was no longer directly inside the text area. Please compare with other editors where it is OK for the mouse to exit the editing region (try for example right here in the comment box for this ticket....). I am marking this as a bug as it really is a noticeable annoyance for end users.

**Comment by dlemmermann** [comment]
The current version does not support the requested selection behaviour.

**Comment by jperedadnr** [comment]
This still works for me. Can you check again?

**Comment by dlemmermann** [comment]
Works for me now, too. I think in one of my last tests I forgot to change the artefact ID to the new one :-)
