### ISSUE TITLE
Index exceeds maxCellCount error

### ISSUE THREAD

**Issue by dlemmermann** [gluonhq/rich-text-area#136]
I am seeing this error message after copy pasting some "Lorem Ipsum" text a couple of times (see https://www.loremipsum.de to generate your own text).  I think a virtual flow should not care about that, should it? It should always only use a few more cells than the ones currently visible, right?

```
Mar 29, 2022 5:13:51 PM javafx.scene.control.skin.VirtualFlow addTrailingCells
INFO: index exceeds maxCellCount. Check size calculations for class com.gluonhq.richtext.RichListCell
```

**Comment by jperedadnr** [comment]
I can't reproduce this. 
@dlemmermann Unless you have an easy way to reproduce it, I'm in favour of closing this issue, or at least removing the MVP milestone for now. Thoughts?

**Comment by dlemmermann** [comment]
I also didn't run into it anymore. Feel free to close.
