### ISSUE TITLE
Lists do not show numbers or bullets

### ISSUE THREAD

**Issue by dlemmermann** [gluonhq/rich-text-area#151]
When marking text rows as a list we are not seeing any graphics representing the items.

**Comment by dlemmermann** [comment]
Looks like the paragraph graphic factory is only set inside the demo app (Main). However, the ParagraphTile class expects a factory to exist inside the graphicFactoryProperty (line 155). Currently I am seeing a NPE.

**Comment by jperedadnr** [comment]
I'm fixing the NPE that happens if user doesn't provide a PGFactory.

@dlemmermann Do you think the control should have a built-in factory by default?

Also, if the indentation level is 0, the list (numbered/bulleted) is not visible. It is visible only if level is >= 1. Do you think the action should enforce level = 1 if `GraphicType.BULLETED` or `GraphicType.NUMBERED` are selected?

**Comment by dlemmermann** [comment]
Yes to both. How / for what would one use a level 0?

**Comment by jperedadnr** [comment]
level 0 is just "no level" of indentation.
For the default factory, numbered list will use "#.", and for bulleted: 
black filled circle, black empty circle, rounded filled square, rounded empty square (and start all over again)?

**Comment by dlemmermann** [comment]
yes, just start all over again.

**Comment by jperedadnr** [comment]
ok, about font size for the label, do you think it should be bound to the paragraph size?
Notes app uses the same size based on the first word font of the paragraph (while shapes remain with same fixed size).
About alignment, label uses some baseline as paragraph, while shapes are centered.

**Comment by dlemmermann** [comment]
Yes, same font size for the labels. 
Labels should be right-aligned I think.

**Comment by jperedadnr** [comment]
Yes, that is the easy part... (right alignment). However, getting the label that belongs to an HBox, align vertically based on the baseline of the first Text node in a TextFlow is another thing...

**Comment by jperedadnr** [comment]
With the ongoing changes:

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/2043230/161712675-7c02f657-ad7e-4ff4-9530-63a8cb41d55c.png">
