### ISSUE TITLE
TextDecoration.Builder should use system font inside presets() method

### ISSUE THREAD

**Issue by dlemmermann** [gluonhq/rich-text-area#195]
The presets should pick up the font family and font size from the machine where the app is running instead of hard-coding it to "Serif 12".

**Comment by dlemmermann** [comment]
It's just that I think that the goal should be that this text area sort of looks and behaves just like the normal TextArea control if the user hasn't done any formatting, yet, neither manually nor via API.

**Comment by erwin1** [comment]
fix now if easy
