### ISSUE TITLE
How to set an initial text style?

### ISSUE THREAD

**Issue by dlemmermann** [gluonhq/rich-text-area#196]
How can an application specify a text decoration style to use for a new document?

**Comment by dlemmermann** [comment]
We changed the title of this ticket because what this is really about is being able to tell the rich text area how to style any newly typed text going forward. It seems that the control is currently assuming that text has to be typed first and then a style can be applied to it.

**Comment by jperedadnr** [comment]
The "new" text added at the beginning of an empty document, or at the end of the existing test already picks the paragraph/text decorations that are set via the toolbar.

**Comment by dlemmermann** [comment]
But I need API to do that, too, don't I?

**Comment by dlemmermann** [comment]
I want to show the editor and start by default with a "title". How can I do that?

**Comment by jperedadnr** [comment]
If you want to have a predefined decoration, so whenever the user starts typing it has just that "title" preset, then you just need to modify the demo to that default (i.e. bold, font size, ...).
I see that NotesApp uses a title format for the first line, and after typing enter it goes to a body format. I wouldn't go there, though.
