### ISSUE TITLE
Performing a drag of an image causes flickering / crazy scrolling.

### ISSUE THREAD

**Issue by dlemmermann** [gluonhq/rich-text-area#207]
When the text area displays a lot of text (extending the viewport area) and the user performs a drag of an image from the outside onto the area the text area starts scrolling like crazy.

**Comment by dlemmermann** [comment]
https://user-images.githubusercontent.com/9534301/167371650-30345654-5bf3-4cde-a957-b1002e234404.mov

**Comment by dlemmermann** [comment]
The video shows several drag and drop attempts resulting in various spontaneous scrolling operations.

**Comment by jperedadnr** [comment]
Once #217 gets integrated, can you verify if the issue still happens?

**Comment by jperedadnr** [comment]
Integrated, when you have the time, please test.

**Comment by dlemmermann** [comment]
This is much better now, but still a tiny scroll happening sometimes when it should not. For example: when I drag an image onto the middle of the area from the right side. Then there should not be a reason for scrolling to happen. Not sure how you implemented it, but are you constantly repositioning the caret so that you know where to insert the image?

**Comment by jperedadnr** [comment]
Yes, the caret follows the image. See https://github.com/gluonhq/rich-text-area/blob/master/src/main/java/com/gluonhq/richtextarea/RichListCell.java#L102
You can try it out by doing a dnd operation and holding steady the image before dropping it. You should see the caret below it (it is not easy though, the label with the image file name is blue as the caret).
