### ISSUE TITLE
Autoscrolling during drag operations

### ISSUE THREAD

**Issue by dlemmermann** [gluonhq/rich-text-area#208]
The text area should scroll up or down when the mouse cursor is close to the top or bottom edges while performing a drag and drop operation.

**Comment by jperedadnr** [comment]
It actually does scroll (but maybe not with 100% accuracy). This ticket however is not compatible with #207 where you say that d&d causes "crazy scrolling"

**Comment by dlemmermann** [comment]
I do want scrolling when reaching the edges of the viewport, .... I do not want scrolling when I drag and drop into the middle of the text.
