### ISSUE TITLE
Add double-click selection functionality

### ISSUE THREAD

**Issue by abhinayagarwal** [gluonhq/rich-text-area#24]
Almost all editors select the current word when double-clicked anywhere on the word.

**Comment by jperedadnr** [comment]
This can be extended to triple-click for selecting the whole line

**Comment by eugener** [comment]
There is a task for that in backlog already .. feel free to use this one instead of the original one

Eugene
________________________________

**Comment by jperedadnr** [comment]
See how [TextInputControl](https://github.com/openjdk/jfx/blob/master/modules/javafx.controls/src/main/java/javafx/scene/control/TextInputControl.java#L709) handles it with a `BreakIterator` from [TextAreaBehavior](https://github.com/openjdk/jfx/blob/master/modules/javafx.controls/src/main/java/com/sun/javafx/scene/control/behavior/TextAreaBehavior.java#L396).

**Comment by jperedadnr** [comment]
Fixed with #36
