### ISSUE TITLE
The equals method on ParagraphDecoration uses the == to compare the TableDecoration member

### ISSUE THREAD

**Issue by MarkHuntleyJames** [gluonhq/rich-text-area#257]
The equals method on ParagraphDecoration uses == to compare the tableDecoration member instead of equals() so erroneoulsy returns false.

that.tableDecoration == tableDecoration; 
should be 
that.tableDecoration.equals(tableDecoration); 

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ParagraphDecoration that = (ParagraphDecoration) o;
        return Double.compare(that.spacing, spacing) == 0 &&
                Double.compare(that.topInset, topInset) == 0 &&
                Double.compare(that.rightInset, rightInset) == 0 &&
                Double.compare(that.bottomInset, bottomInset) == 0 &&
                Double.compare(that.leftInset, leftInset) == 0 &&
                that.indentationLevel == indentationLevel &&
                that.graphicType == graphicType &&
                that.alignment == alignment &&
                that.tableDecoration == tableDecoration; 
    }

**Comment by jperedadnr** [comment]
Fixed with #260
