### ISSUE TITLE
Appending text can't be undone

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/rich-text-area#26]
Appending text at the end of the current piece can't be undone.
Logging the actions, both append and insert are called when the text is appended, but when undo is called, none of them are called, only the caret is moved to its correct position.

The undoStack includes the append and then the insert commands. Calling undo only pops the insert command, but since `execSuccess` is false, `insert::undo` is not executed.

**Comment by eugener** [comment]
I think I know what the issue is... 
On `document` we have 3 operations: append, insert and delete. On `view model` we only have insert and delete -  that is not specific enough to deal with append nicely. 
Will look into it.

**Comment by jperedadnr** [comment]
Yes, I figured that out, so I was trying to do "append" from RichTextAreaViewModel:

```
void insert( String text ) {
        removeSelection();
        if (getCaretPosition() == getTextLength()) {
            textBuffer.append(text);
        } else {
            textBuffer.insert(text, getCaretPosition());
        }
        moveCaretPosition(1);
    }
```
Does it make sense here?

**Comment by eugener** [comment]
That is exactly what I just did in my branch! :)
