### ISSUE TITLE
Paragraph spacing on open document too big

### ISSUE THREAD

**Issue by tonydroy** [gluonhq/rich-text-area#292]
The spacing between paragraphs from a newly opened document is greater than that which obtains when editing.  In the full-featured demo, replace the "Lorem Ipsum" document with something simple, say "this is\n a test".  Run the demo and open the document; then in the editor type any character at the end of the upper paragraph.  The spacing between the paragraphs is now smaller than in the originally opened document. Once this happens, saving and reopening the document can result in an out of bounds exception in PieceTable - from the same location as commit 270 "fix issue with accumulated length".

**Comment by jperedadnr** [comment]
This should be fixed with #332 
Can you try with the latest snapshot 1.1.4-SNAPSHOT?
