### ISSUE TITLE
The caret is not shown sometimes after undo typing

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/rich-text-area#302]
After typing some characters, when undoing the typing, sometimes the caret is not shown.

After some debugging, it seems that `ParagraphTile::getParagraphLimit` doesn't always provide the correct value, because it queries `RichTextAreaSkin::lastParagraph`, which might not be up to date all the time (it is only refreshed from `RichTextAreaSkin::refreshTextFlow`, which doesn't get called all the time).

**Comment by abhinayagarwal** [comment]
I am unable to reproduce the issue. Tried typing and then undo, carat is always showing. Are there specific ways to reproduce the issue?
