### ISSUE TITLE
Hard to click with mouse to the right of the text

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/rich-text-area#31]
Even there is a lot of space to the right of the last character, mouse only works if it is strictly over the textFlow.
<img width="228" alt="image" src="https://user-images.githubusercontent.com/2043230/153925678-3e277974-a79f-4d51-9db7-845eb2933860.png">

**Comment by eugener** [comment]
I think clicking anywhere on empty space should set the caret to the end of the text

**Comment by jperedadnr** [comment]
Yes, we need to expand the TextFlow to take the whole scrollPane area, without causing the scrollbars to be visible.

**Comment by jperedadnr** [comment]
We have a mouse listener added to the TextFlow, and then hitInfo helps to set the caret location. We don't have the same for the ScrollPane, so that would require another mouse listener, to find the closest position (end of some given line) and then to forward the event to textFlow?

**Comment by jperedadnr** [comment]
expanding the textFlow seems easier. We just need to set pref size based on scrollPane size - bars.

**Comment by eugener** [comment]
I was thinking that on any click to ScrollPane we just set the caret to the end of the text... what can be simpler? 
Keeping up with pref size is harder I thought

**Comment by jperedadnr** [comment]
Adding the same mouse pressed listener to the scrollpane works almost fine: it does send the caret to the end of the closest line. However, that should also set work for selection, but it doesn't, and if you start dragging from outside the textFlow, there won't be any selection.

Alternatively, we can add more padding to the Textflow to right and bottom?

```
textFlow.setPadding(new Insets(-1, 10, 5, -1));
```

<img width="193" alt="image" src="https://user-images.githubusercontent.com/2043230/153934043-36b29749-41a3-4c74-8b2d-409c293b188d.png">

**Comment by eugener** [comment]
I wonder of we catch mouse leaving the text flow and keep caret at the last position it was

**Comment by jperedadnr** [comment]
On an IDE, all area is clickable, cursor is set to TEXT, and you can drag from anywhere. This can be achieved only if we make the TextFlow take the whole area (without showing the scrollbars).
One easy fix is to replace `Group layers` with `Pane layers`, which is resizable, and then add the mouse listeners to `layers` instead of `textFlow`.

**Comment by jperedadnr** [comment]
I've spent some time on this... the Pane is proposed here: https://github.com/jperedadnr/rich-text-area/tree/31-resize
I was about to create a PR, but that won't work...

- For starters, there is a bug when the TextFlow is part of the Pane, and the caret goes to the next line when it shouldn't. For now I fixed it setting the prefWidth, but that is something I wanted to avoid.

- Since the scrollPane is set to fill height and width, the content is always wrapped and there are no scrollbars. Removing this will cause content not wrapped... but without scrollbars anyway.

The TextFlow is a container that works fine for its purpose, but it is not a good node for a ScrollPane. 

Reviewing the TextArea control, internally it uses a ScrollPane and a tailored container, the [ContentView](https://github.com/openjdk/jfx/blob/master/modules/javafx.controls/src/main/java/javafx/scene/control/skin/TextAreaSkin.java#L1209), which does the functions of the TextFlow (i.e managing Text nodes, caret and selection, mouse handling) and also plays nicely with the scrollPane (allowing wrapped and non-wrapped content).

I'm not sure if we can get the same functionality extending the TextFlow and overriding some of its methods...
@eugener thoughts?

**Comment by eugener** [comment]
`ContentView` is a private class so cannot be used as of now. 
I have no idea if it is possible get `TextFlow`  to work in a similar way, but it is worth trying IMO.

**Comment by jperedadnr** [comment]
I know, and doing a custom solution with TextFlow will have to use only public methods, so it can be quite limited.

**Comment by eugener** [comment]
It sill have some advantages since you can use protected  code from `TextFlow`... not sure if that helps though

**Comment by jperedadnr** [comment]
Got a fix for this now with https://github.com/gluonhq/rich-text-area/pull/66. It works fine, and there is no need for a custom TextFlow.
