### ISSUE TITLE
How do I get the input text

### ISSUE THREAD

**Issue by yyyyyyyysssss** [gluonhq/rich-text-area#344]
richTextArea.getDocument().getText() return null

**Comment by jperedadnr** [comment]
I take that you start from an empty document, make some changes, and then the text is empty/null? Else please provide a better description of the issue, and how to reproduce it.

If you don't set `RichTextArea::setAutoSave` to true, the document changes are not saved, until you call  save() via `rta.getActionFactory().save().execute(new ActionEvent())`.

**Comment by yyyyyyyysssss** [comment]
> I take that you start from an empty document, make some changes, and then the text is empty/null? Else please provide a better description of the issue, and how to reproduce it.
> 
> If you don't set `RichTextArea::setAutoSave` to true, the document changes are not saved, until you call save() via `rta.getActionFactory().save().execute(new ActionEvent())`.

set RichTextArea::setAutoSave is work thank you

**Comment by yyyyyyyysssss** [comment]
> I take that you start from an empty document, make some changes, and then the text is empty/null? Else please provide a better description of the issue, and how to reproduce it.
> 
> If you don't set `RichTextArea::setAutoSave` to true, the document changes are not saved, until you call save() via `rta.getActionFactory().save().execute(new ActionEvent())`.

How do I clear the input information？

**Comment by yyyyyyyysssss** [comment]
By setting up a new document? But text messages were not erased
