### ISSUE TITLE
How do I change the line feed button

### ISSUE THREAD

**Issue by yyyyyyyysssss** [gluonhq/rich-text-area#345]
The document does not provide an operation to append newlines；
richTextArea.setOnKeyPressed not work

**Comment by jperedadnr** [comment]
New lines are just added by the user when pressing the Enter key. 
Do you want to add them programmatically?

**Comment by yyyyyyyysssss** [comment]
> 用户只需按下 Enter 键即可添加新行。 您想通过编程添加它们吗？

I want to change to shift+enter for line wrapping; The enter key triggers other events, so there's a way to change that

**Comment by yyyyyyyysssss** [comment]
> 用户只需按下 Enter 键即可添加新行。 您想通过编程添加它们吗？

Yes, but richTextArea. SetOnKeyPressed doesn't work, when press any key the event will not be triggered

**Comment by jperedadnr** [comment]
As I mentioned in this other issue #347 , you shouldn't use `setOnKeyPressed`.

`Shift+Enter` already works for adding a new line, and `RichTextArea::setOnAction` allows you to:

> Defines the action to be performed when enter is pressed. If no action is set, a new line will be added by default.

So if you set it to something other than null, like
```
richTextArea.setOnAction(e -> {}); // do nothing on Enter
```
this will not add a new line on Enter.

**Comment by yyyyyyyysssss** [comment]
> 正如我在另一个问题#347中提到的，您不应该使用`setOnKeyPressed`。
> 
> `Shift+Enter`已经可以添加新行，其中包括`RichTextArea::setOnAction`：
> 
> > 定义回车键时执行的操作。如果没有设置操作，则默认添加新行。
> 
> 因此，如果你将其设置为null除此之外的其他值，
> 
> ```
> richTextArea.setOnAction(e -> {}); // do nothing on Enter
> ```
> 
> 这将不会在 Enter 时添加新行。

thanks
