### ISSUE TITLE
How to get the text nodes and picture nodes in the document

### ISSUE THREAD

**Issue by yyyyyyyysssss** [gluonhq/rich-text-area#348]
All you get through richTextArea.getDocument().gettext () is the text. Is there an easy way to get text nodes and picture nodes? Or is it necessary to extract the text through a regular expression after obtaining it

**Comment by jperedadnr** [comment]
Getting the nodes of the scene graph is not part of the RTA API.

However, like every node, you can use lookups.

For every paragraph there is a `TextFlow` node, and you can easily get access to its nodes:

```
    richTextArea.lookupAll(".text-flow")
                .forEach(n -> System.out.println("Nodes: " + ((TextFlow) n).getChildrenUnmodifiable()));
```
