### ISSUE TITLE
Improve Text Decoration action

### ISSUE THREAD

**Issue by eugener** [gluonhq/rich-text-area#37]
- [ ] - Respect the other decoration attributes
- [ ] - Toggle the decoration attribute if it is already set for font weight and posture
- [ ] - Fix the  JavaDoc on `PieceTable.TextDecorateCmd`

**Comment by abhinayagarwal** [comment]
> Respect the other decoration attributes

This needs to pass data via the EditorAction i.e. from the Skin into the ViewModel. Therefore, will be better to be taken care of as a part of #5 

For the other 2 enhancements, I have created #38

**Comment by eugener** [comment]
What I meant here is that if we have red, bold, italic text, and we hit `ctrl-B` to bold it, it should only bold/unbold it, and leave red, italic etc untouched.

**Comment by abhinayagarwal** [comment]
Since TextDecoration builder has defaults, there is no way to differentiate if a TextDecoration property was set by user or is present by default. Should we update TextDecoration.Builder to only return data for the value set by the user?

**Comment by eugener** [comment]
I don't think it matters? We update whatever is set now. 
It i possible that for defaults every attribute has to be set to default value

**Comment by abhinayagarwal** [comment]
For example, I have a text with following text decoration:

```
TextDecoration { fontWeight=BOLD, fontPosture=REGULAR }
```

And then the user applies ITALIC posture to it. Since, we have defaults set, The TextDecoration definition generated by the builder would be:

```
TextDecoration { fontWeight=NORMAL, fontPosture=ITALIC }
```

Now, how do you decide if `fontWeight=NORMAL` is to be applied or not?

**Comment by eugener** [comment]
Ah... I see.  Check related discussion here https://github.com/gluonhq/rich-text-area/pull/38#issuecomment-1042993030

**Comment by abhinayagarwal** [comment]
Yes, https://github.com/gluonhq/rich-text-area/pull/38#issuecomment-1042993030 could actually simplify what we are trying to achieve here.
