### ISSUE TITLE
Resizing text area causes scrollbar flickering

### ISSUE THREAD

**Issue by dlemmermann** [gluonhq/rich-text-area#95]
When resizing the window of the demo app (Main) one can see the scrollbar flicker.

**Comment by dlemmermann** [comment]
Additional info: when no text is entered, or text is not fully using the visible area.

**Comment by jperedadnr** [comment]
If there is no text, there shouldn't be a scrollbar. Can you maybe post a small video?

**Comment by dlemmermann** [comment]
https://user-images.githubusercontent.com/9534301/157429076-07121974-bc45-4372-9789-379c475e8591.mov

**Comment by dlemmermann** [comment]
After switching to a ListView this issue is no longer present.
