### ISSUE TITLE
Rich text area causes shaking / flickering in UI

### ISSUE THREAD

**Issue by dlemmermann** [gluonhq/rich-text-area#99]
We started first tests of the rich text area inside the customer's project and we noticed that the UI starts "shaking". I am assuming that this is caused by a layout pass that resizes a child larger than "allowed", triggering a subsequent (and infinite) relayout. The flickering can be nicely seen in this video.

https://user-images.githubusercontent.com/9534301/157844253-66e48b92-c5ca-4312-95b8-be50be921e9e.mov

This has been tested with the latest changes as of today, March 11th.

**Comment by jperedadnr** [comment]
Can you provide a little insight of the JavaFX containers/nodes hierarchy you are using?

**Comment by dlemmermann** [comment]
Highly proprietary. :-) This is using the docking framework I developed for the customer, so I can't make it available unfortunately. I tried replacing the rich text area with a regular text area to see if the issue would also show up there, but it did not.

**Comment by dlemmermann** [comment]
But I can get rid of the flickering by adding more margin of error to the pref height / width bindings created inside the RichAreaTextSkin. 

```java
        prefWidthBinding = Bindings.createDoubleBinding(() ->
                        getSkinnable().getContentAreaWidth() > 0 ?
                                getSkinnable().getContentAreaWidth() : scrollPane.getViewportBounds().getWidth() - 10,
                getSkinnable().contentAreaWidthProperty(), scrollPane.viewportBoundsProperty());
        prefHeightBinding = Bindings.createDoubleBinding(() -> scrollPane.getViewportBounds().getHeight() - 10,
                scrollPane.viewportBoundsProperty());
```
I think those bindings do not consider changes to the styling of the viewport / scrollpane.

**Comment by jperedadnr** [comment]
Do you think we should consider viewport's padding into the binding, or use a more simple approach and keep this "10" as safe margin?

**Comment by dlemmermann** [comment]
Definitely consider the viewport's padding.

**Comment by jperedadnr** [comment]
I don't think viewport's padding is the root cause of this issue. The viewport is a non-managed node, and adding padding to it doesn't apply to the content, which is laid out regardless this padding. See a TextArea for instance.
The viewport already considers the scrollpane padding in its bounds.
What "visible" styling do you apply to the viewport? Do you see it?

**Comment by dlemmermann** [comment]
There is also the content-area pane. I changed the pref width / height binding to observe the insets of that pane and now the flickering is gone. For some reason the change was merged with my previous JPRO request and I do not know how to create a new PR with just that one change.

**Comment by jperedadnr** [comment]
That's because you are doing the PR from your master repository. For each issue, it is better to create a branch in your own repository, apply only the required changes on it, and then create the PR from that branch against the master of this repo.

**Comment by dlemmermann** [comment]
Yeah, that's what I thought. Maybe we please skip this for now?

**Comment by jperedadnr** [comment]
Note that  `root` Pane and `textFlow` are bound to have the same size, and padding the root doesn't have any effect over the textFlow.
The proposed changes to consider `root.insetsProperty()`, will affect both the root and textFlow.
For instance:

```
.rich-text-area .content-area {
    -fx-background-color: white;
    -fx-border-color: black;
    -fx-padding: 40;
}
```

<img width="912" alt="image" src="https://user-images.githubusercontent.com/2043230/157873313-dc17c7d7-fa1a-4e8b-96e8-7e97775cf369.png">
 
Even if that fixes the flickering, I don't think that's the correct fix.

**Comment by dlemmermann** [comment]
I encountered another case of shaking / flickering where I was editing the content of the document and all of a sudden the layout process / the bindings started going crazy. Resizing the window stops the flickering.

https://user-images.githubusercontent.com/9534301/158805287-b1d21da6-0bc9-49a5-b72c-927954ee1a80.mov

**Comment by dlemmermann** [comment]
After the switch to ListView I could not longer reproduce this issue.
